---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adwmock
  namespace: default
  labels:
    app: adwmock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adwmock
  template:
    metadata:
      labels:
        app: adwmock
    spec:
      containers:
        - name: web
          image: docker.io/library/adwmock:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
            requests:
              cpu: 10m
              memory: 32Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        seccompProfile:
          type: RuntimeDefault
---
apiVersion: v1
kind: Service
metadata:
  name: adwmock-svc
  namespace: default
spec:
  selector:
    app: adwmock
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adwmock
  namespace: default
spec:
  defaultBackend:
    service:
      name: adwmock-svc
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - adwmock
