import type { AdwNodeType } from "../types/mockup";

/**
 * The widget catalog shared by the command palette (Ctrl+K) and the
 * draggable widget palette in the left panel (#79). One list, so a widget
 * added to Protota shows up in both insertion surfaces.
 */
export const ALL_WIDGETS: { type: AdwNodeType; label: string; desc: string }[] = [
  { type: "button", label: "Button", desc: "Clickable button" },
  { type: "window-title", label: "Window Title", desc: "Title + subtitle" },
  { type: "box", label: "Box", desc: "Directional container" },
  { type: "label", label: "Label", desc: "Text" },
  { type: "list-box", label: "List Box", desc: "Boxed-list container" },
  { type: "clamp", label: "Clamp", desc: "Max-width container" },
  { type: "header-bar", label: "Header Bar", desc: "Title bar with buttons" },
  { type: "action-row", label: "Action Row", desc: "Title + subtitle + suffix" },
  { type: "switch-row", label: "Switch Row", desc: "Toggle switch row" },
  { type: "combo-row", label: "Combo Row", desc: "Dropdown row" },
  { type: "entry-row", label: "Entry Row", desc: "Text input row" },
  { type: "status-page", label: "Status Page", desc: "Empty/error/loading" },
  { type: "banner", label: "Banner", desc: "Persistent info bar" },
  { type: "progress-bar", label: "Progress Bar", desc: "Determinate progress" },
  { type: "scale", label: "Scale", desc: "Slider" },
  { type: "level-bar", label: "Level Bar", desc: "Capacity meter" },
  { type: "drop-down", label: "Drop Down", desc: "Standalone selector" },
  { type: "avatar", label: "Avatar", desc: "User or contact image" },
  { type: "wrap-box", label: "Wrap Box", desc: "Reflowing horizontal box" },
  { type: "popover", label: "Popover", desc: "Surface attached to a widget" },
  { type: "list-box-row", label: "List Row", desc: "Plain boxed-list row" },
  { type: "grid", label: "Grid", desc: "Rows and columns" },
  { type: "scrolled-window", label: "Scrolled Window", desc: "Viewport with overflow" },
  { type: "stack", label: "Stack", desc: "One visible page at a time" },
  { type: "bin", label: "Bin", desc: "Single-child container" },
  { type: "toast-overlay", label: "Toast Overlay", desc: "Toast container" },
  { type: "spinner", label: "Spinner", desc: "Loading indicator" },
  { type: "entry", label: "Entry", desc: "Text input" },
  { type: "search-entry", label: "Search Entry", desc: "Search bar" },
  { type: "toggle", label: "Toggle", desc: "Pill toggle button" },
  { type: "preferences-group", label: "Preferences Group", desc: "Titled section" },
  { type: "spin-row", label: "Spin Row", desc: "Numeric spinner row" },
  { type: "button-row", label: "Button Row", desc: "Clickable action row" },
  { type: "expander-row", label: "Expander Row", desc: "Expandable row" },
  { type: "password-row", label: "Password Row", desc: "Password input row" },
  { type: "center-box", label: "Center Box", desc: "Start/center/end" },
  { type: "flow-box", label: "Flow Box", desc: "Wrapping grid" },
  { type: "inscription", label: "Inscription", desc: "Text w/ ellipsis" },
  { type: "menu-button", label: "Menu Button", desc: "Icon button w/ popover" },
  { type: "split-button", label: "Split Button", desc: "Button + dropdown" },
  { type: "switch-widget", label: "Switch", desc: "Binary toggle" },
  { type: "check-button", label: "Check Button", desc: "Checkbox" },
  { type: "toggle-group", label: "Toggle Group", desc: "Group of toggles" },
  { type: "view-stack", label: "View Stack", desc: "Switched pages" },
  { type: "tab-view", label: "Tab View", desc: "Multi-document tabs" },
  { type: "overlay-split", label: "Overlay Split", desc: "Sidebar + content" },
  { type: "view-switcher", label: "View Switcher", desc: "Flat tab bar" },
  { type: "navigation-view", label: "Navigation View", desc: "Push/pop nav" },
  { type: "preferences-page", label: "Preferences Page", desc: "Tab in prefs dialog" },
  { type: "toolbar-view", label: "Toolbar View", desc: "Header + content + bottom" },
];
